"""Sound direction brief and presentation triggers, never game rules."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Cue:
    id: str
    title: str
    group: str
    modes: tuple
    description: str
    trigger: str
    hook: str
    recipe: str
    material: str
    notes: tuple
    duration: float
    legacy: str | None = None
    variants: int = 1
    optional: bool = False
    highlight: bool = False


BOTH = ("classic", "gauntlet")
CLASSIC = ("classic",)
GAUNTLET = ("gauntlet",)

STYLES = {
    "studio": {
        "name": "A / Studio",
        "short": "Studio",
        "tagline": "Close, tactile, collectible.",
        "description": (
            "Real card and chip textures, felt-soft impacts, restrained tuned glass. "
            "A small, warm room rather than an arcade. The everyday-play recommendation."
        ),
        "color": "#f2c078",
    },
    "mythic": {
        "name": "B / Mythic",
        "short": "Mythic",
        "tagline": "Weight, motion, a little magic.",
        "description": (
            "The same physical foundation, with granular air, bowed resonances, "
            "pitched impacts and a wider, diffuse tail. Best reserved for big reveals and Gauntlet stakes."
        ),
        "color": "#a99bff",
    },
}

GROUPS = {
    "interface": "Interface",
    "cards": "Cards & packs",
    "economy": "Trading",
    "grading": "Grading",
    "collection": "Collection",
    "run": "Gauntlet / the run",
    "catalysts": "Gauntlet / Catalysts",
    "upgrades": "Gauntlet / upgrades",
    "outcomes": "Victories & setbacks",
}

# Notes are MIDI pitches, not borrowed melodies. Related actions share a palette,
# but have different material gestures, rhythms and harmonic resolutions.
CUES = (
    Cue("ui_tap", "Select / navigate", "interface", BOTH,
        "A fingertip-sized, rounded material click. No notification beep.",
        "Navigation, tabs, filters, share and ordinary confirmations; not every animation.",
        "Views/MainMenuView.swift; Views/CollectionView.swift; Views/BinderView.swift",
        "touch", "chip", (74,), 0.18, variants=3),
    Cue("ui_back", "Back / dismiss", "interface", BOTH,
        "A brushed, falling response that feels lighter than selecting.",
        "Back, sheet dismissal, cancel and returning home. Never on autosave.",
        "Views/MainMenuView.swift; Views/GauntletView.swift",
        "slide", "slide", (65,), 0.26),
    Cue("panel_open", "Inspect a card", "interface", BOTH,
        "A close paper lift with a tiny glass focus point.",
        "Open a card, Showcase detail, Binder detail, or Settings panel.",
        "Views/CardDetailView.swift; Views/GauntletRunViews.swift; Views/SettingsView.swift",
        "slide", "card", (69, 76), 0.38),
    Cue("toggle_on", "Setting confirmed", "interface", BOTH,
        "A two-part switch detent, deliberately quiet.",
        "Explicitly enabling sound or changing a setting; disabling sound stays silent.",
        "Views/SettingsView.swift",
        "touch", "chip", (72, 79), 0.26, legacy="coin"),
    Cue("blocked", "Action unavailable", "interface", BOTH,
        "A cushioned double knock. Informative, never an angry buzzer.",
        "A rejected action with visible feedback; no sound from an already-disabled control.",
        "Views/ShopView.swift; Views/CardDetailView.swift; Views/GauntletRunViews.swift",
        "blocked", "chip", (50, 48), 0.38),
    Cue("pack_open", "Tear open a pack", "cards", BOTH,
        "A grip, two irregular foil tears, a card fan and a weighted release.",
        "SealedPackView.open, aligned to the tear. The first card has no extra flip.",
        "Views/RevealAnimation.swift: SealedPackView.open",
        "tear", "fan", (), 0.86, legacy="pack_open", variants=3, highlight=True),
    Cue("card_flip", "Turn the next card", "cards", BOTH,
        "A dry card slide, air displacement and a soft edge landing.",
        "RevealingCardView.run only when playFlipSound is true.",
        "Views/RevealAnimation.swift: RevealingCardView.run",
        "slide", "slide", (), 0.24, legacy="card_flip", variants=3, highlight=True),
    Cue("new_card", "A new discovery", "cards", BOTH,
        "A small, warm harmonic glint, not a second rarity fanfare.",
        "Optional NEW badge accent on ordinary cards; suppress under rare/ultra/foil.",
        "Views/RevealAnimation.swift: RevealingCardView.newBadge",
        "glint", "card", (76, 83), 0.60, optional=True),
    Cue("foil", "Foil light sweep", "cards", BOTH,
        "Soft metallic grains opening into a silky, moving halo.",
        "At face-up with the foil sheen. A quiet overlay, not another impact.",
        "Views/RevealAnimation.swift: RevealingCardView.run",
        "shimmer", "slide", (81, 88, 95), 1.48, legacy="foil_shimmer", highlight=True),
    Cue("rare", "Rare reveal", "cards", BOTH,
        "A reversed breath, a luminous struck chord and a restrained tail.",
        "At face-up for a rare; may overlap the foil overlay.",
        "Views/RevealAnimation.swift: RevealingCardView.run",
        "reveal", "card", (62, 69, 76, 81), 1.48, legacy="rare", highlight=True),
    Cue("ultra", "Ultra reveal", "cards", BOTH,
        "A deep, phone-readable impact, widening harmonic bloom and falling flecks.",
        "At face-up for an ultra; takes priority over routine interface sounds.",
        "Views/RevealAnimation.swift: RevealingCardView.run",
        "reveal", "stack", (50, 62, 69, 78, 85), 2.45, legacy="ultra", highlight=True),
    Cue("keep_card", "Keep / add to collection", "cards", BOTH,
        "A card settles on felt and locks into place.",
        "After Keep succeeds; one cue for Keep All, not one per card.",
        "Views/RevealView.swift: decideKeep; Models/GauntletState.swift: keep",
        "place", "card", (62, 69), 0.36, variants=3),
    Cue("sell_card", "Sell a card", "economy", BOTH,
        "A card leaves the table; a few chips settle with a soft metallic tick.",
        "Only after a successful sale, in either mode.",
        "Views/CardDetailView.swift; Views/RevealView.swift; Models/GauntletState.swift: sell",
        "coins", "chip", (81, 88), 0.57, legacy="coin", variants=3, highlight=True),
    Cue("pack_purchase", "Buy a pack", "economy", CLASSIC,
        "A compact payment click followed by the physical arrival of a pack.",
        "After buyPack succeeds, before the player tears the wrapper.",
        "Views/ShopView.swift: buyPack / buyBox",
        "purchase", "stack", (69, 78), 0.62, legacy="purchase"),
    Cue("bulk_sell", "Sell duplicates", "economy", CLASSIC,
        "An uneven, accelerating chip count with a clean final settle.",
        "One bounded cue per bulk sale, regardless of the duplicate count.",
        "Views/RevealView.swift: sellAllPending / sellDuplicates",
        "coins", "stack", (74, 81, 86), 0.96, legacy="coin"),
    Cue("grade_start", "Submit for grading", "grading", BOTH,
        "A sleeve slide, mechanical latch and short tension bed.",
        "On a successful grading request. Do not delay or reroll the existing result.",
        "Views/CardDetailView.swift; Views/RevealView.swift; Views/GauntletRunViews.swift: gradeSection",
        "stamp", "card", (57, 64), 0.63),
    Cue("grade_low", "Grade / value down", "grading", BOTH,
        "A muted slab stamp and a sympathetic, unresolved lower interval.",
        "Result lowers value/Aura; choose by the actual result, not a guessed grade threshold.",
        "Views/CardDetailView.swift: GradeRevealOverlay; Views/GauntletRunViews.swift: gradeSection",
        "grade", "chip", (57, 60, 64), 0.94),
    Cue("grade_high", "Grade / solid result", "grading", BOTH,
        "A precise slab click resolving into warm, restrained consonance.",
        "Non-PSA-10 result with neutral or increased value/Aura.",
        "Views/CardDetailView.swift: GradeRevealOverlay; Views/GauntletRunViews.swift: gradeSection",
        "grade", "chip", (62, 69, 76), 1.10),
    Cue("grade_perfect", "Grade / gem mint 10", "grading", BOTH,
        "A crisp seal, jewel-like bloom and soft upper-octave dust.",
        "PSA 10 only, when the result is visible; replaces the ordinary result cue.",
        "Views/CardDetailView.swift: GradeRevealOverlay; Views/GauntletRunViews.swift: gradeSection",
        "reveal", "chip", (62, 74, 81, 86, 90), 1.95, highlight=True),
    Cue("evolution_complete", "Evolution line complete", "collection", BOTH,
        "Three linked material strikes join into one resonant chord.",
        "Classic BonusEvent.evolution or a newly completed Showcase line; once per new line.",
        "Views/RevealView.swift: updateEvoBanners; Models/GauntletCore.swift: completedShowcaseLineIds",
        "progress", "card", (62, 69, 76), 1.52),
    Cue("binder_upgrade", "Binder best copy improved", "collection", BOTH,
        "A page settles and a small gold highlight catches the light.",
        "Optional visible Binder improvement only; never for background persistence or loading.",
        "Models/GameState.swift: recordBinder / recordGauntletCards; Views/BinderView.swift",
        "glint", "fan", (69, 81), 0.82, optional=True),
    Cue("set_unlock", "A new set opens", "collection", CLASSIC,
        "A latch releases, followed by an inviting rising harmonic door.",
        "Only when progression newly makes a set available, not on every shop appearance.",
        "Models/GameState.swift: isSetUnlocked; Views/ShopView.swift",
        "unlock", "chip", (57, 64, 69, 76), 1.38),
    Cue("set_complete", "Set complete / bonus", "collection", CLASSIC,
        "A full binder closes with weight, then a generous but compact reward.",
        "BonusEvent.set when its completion banner becomes visible.",
        "Views/RevealView.swift: BonusBanner",
        "progress", "stack", (50, 62, 69, 78, 81), 2.10),
    Cue("classic_win", "Classic / collection complete", "outcomes", CLASSIC,
        "A substantial, warm finale with a resolved harmonic crest and a graceful release.",
        "WinView first presentation, after the pack summary; never again when browsing a completed save.",
        "Views/WinView.swift; Models/GameState.swift: presentsWin",
        "victory", "stack", (50, 57, 62, 69, 78, 86), 3.15, highlight=True),
    Cue("classic_loss", "Classic / out of funds", "outcomes", CLASSIC,
        "The table gently settles into a low, open chord. No mocking fail sting.",
        "LoseView first presentation after reveals finish; not on every failed purchase.",
        "Views/LoseView.swift; Models/GameState.swift: presentsGameOver",
        "defeat", "card", (50, 57, 60, 65), 1.95),
    Cue("trainer_select", "Choose a Trainer", "run", GAUNTLET,
        "A deliberate card placement with a small signature resonance.",
        "After selecting an unlocked Trainer.",
        "Models/GauntletState.swift: chooseTrainer",
        "place", "card", (57, 64, 69), 0.66),
    Cue("tier_select", "Choose difficulty", "run", GAUNTLET,
        "A firm two-part lock-in; more substantial than a navigation tap.",
        "Tier confirmation, before the run-start cue; never on a locked tier.",
        "Views/GauntletView.swift; Models/GauntletState.swift: startRun",
        "stamp", "chip", (50, 57), 0.57),
    Cue("run_start", "Enter the Gauntlet", "run", GAUNTLET,
        "A short gathering of air opens into a low, confident arena pulse.",
        "First ripping screen of a newly created run; not a restored run.",
        "Models/GauntletState.swift: startRun",
        "arrival", "stack", (38, 50, 57, 64), 1.74),
    Cue("round_start", "Next round", "run", GAUNTLET,
        "A tight forward sweep and a focused, pitched impact.",
        "Leaving the shop for a normal round; skip if the round immediately auto-clears.",
        "Models/GauntletState.swift: continueFromShop",
        "arrival", "card", (50, 62, 69), 1.03),
    Cue("boss_round", "Enter the Championship", "run", GAUNTLET,
        "A larger inhale, two weighted hits and suspended upper harmonics.",
        "Championship entry replaces round_start; no extra alarm loop.",
        "Views/GauntletRunViews.swift: championshipSubtitle / Enter the Championship",
        "arrival", "stack", (38, 45, 50, 61, 69), 2.20, highlight=True),
    Cue("last_rip", "One rip remaining", "run", GAUNTLET,
        "A soft paired material pulse, legible without an electronic alarm.",
        "Optional once-per-round warning when ripsLeft changes to one; defer until after the reveal.",
        "Models/GauntletCore.swift: ripsLeft; Views/GauntletRunViews.swift",
        "blocked", "card", (57, 64), 0.55, optional=True),
    Cue("showcase_swap", "Swap a Showcase card", "run", GAUNTLET,
        "One card sweeps out, another seats, and the exchange clicks closed.",
        "After swap succeeds; replaces keep/sell sounds for this compound action.",
        "Models/GauntletState.swift: swap",
        "swap", "slide", (62, 74), 0.63),
    Cue("aura_gain", "Aura increases", "run", GAUNTLET,
        "A subtle breath through tuned resonators; intentionally not a score-counting beep.",
        "Optional short meter accent; suppress if a line completion or round clear fires.",
        "Models/GauntletCore.swift: showcaseAura; Views/GauntletRunViews.swift",
        "aura", "slide", (69, 76, 83), 0.67, variants=3, optional=True),
    Cue("catalyst_offer", "Catalyst discovered", "catalysts", GAUNTLET,
        "A dry crackle unfolds into a hovering, inharmonic crystal.",
        "Catalyst face-up reveal, with its own identity rather than a reused rare sting.",
        "Views/GauntletRunViews.swift: Catalyst reveal",
        "magic", "chip", (57, 69, 76, 83), 1.45, legacy="rare", highlight=True),
    Cue("catalyst_attune", "Attune a Catalyst", "catalysts", GAUNTLET,
        "A spiral of grains pulls inward and lands in a stable resonant core.",
        "After attunePendingCatalyst succeeds; distinct from merely discovering it.",
        "Models/GauntletState.swift: attunePendingCatalyst",
        "magic", "stack", (50, 62, 69, 78), 1.48, highlight=True),
    Cue("catalyst_swap", "Replace a Catalyst", "catalysts", GAUNTLET,
        "One resonance exhales while the new one locks into its place.",
        "After swapPendingCatalyst succeeds; the discarded Catalyst earns no sale cue.",
        "Models/GauntletState.swift: swapPendingCatalyst",
        "swap", "chip", (57, 64, 76), 1.08),
    Cue("catalyst_sell", "Sell a Catalyst", "catalysts", GAUNTLET,
        "A short magical dissolution contracts into physical payment.",
        "After sellPendingCatalyst succeeds, in place of the ordinary sale cue.",
        "Models/GauntletState.swift: sellPendingCatalyst",
        "coins", "chip", (76, 81, 88), 0.96),
    Cue("round_clear", "Aura target reached", "run", GAUNTLET,
        "An immediate, affirmative impact with a rising harmonic crest.",
        "First confettiBurst for this round, including mid-summary; never repeat when entering the shop.",
        "Models/GauntletState.swift: evaluateRoundProgress / confettiBurst",
        "progress", "stack", (50, 62, 69, 81), 1.40, highlight=True),
    Cue("round_payout", "Bank the round payout", "upgrades", GAUNTLET,
        "Three uneven chip deposits settle into one cash-ledger close.",
        "Once when the shop ledger appears; combine interest, stipend and unused-rip bank.",
        "Views/GauntletRunViews.swift: ledger / lastInterest / lastStipend / lastRipBank",
        "coins", "stack", (69, 76, 81), 1.02),
    Cue("showcase_expand", "Buy a Showcase slot", "upgrades", GAUNTLET,
        "A physical rail opens, a detent seats and a warm accent marks the new space.",
        "After buySlot returns true.",
        "Models/GauntletState.swift: buySlot",
        "unlock", "card", (50, 62, 69), 0.95),
    Cue("catalyst_expand", "Buy a Catalyst slot", "upgrades", GAUNTLET,
        "An open mechanical socket meets a quiet crystal resonance.",
        "After buyCatalystSlot returns true.",
        "Models/GauntletState.swift: buyCatalystSlot",
        "unlock", "chip", (57, 69, 78), 1.12),
    Cue("pack_unlock", "Unlock an element pack", "upgrades", GAUNTLET,
        "A solid lock releases into a broad but short invitation.",
        "After unlockPack succeeds in the between-round shop.",
        "Models/GauntletState.swift: unlockPack",
        "unlock", "stack", (50, 57, 69, 76), 1.30),
    Cue("gauntlet_win", "Gauntlet / victory", "outcomes", GAUNTLET,
        "Layered arena weight, a resolved chord and a wide, luminous release.",
        "Final-round win after the reveal closes; not again on the results screen.",
        "Models/GauntletState.swift: endRound / rollReward",
        "victory", "stack", (38, 50, 57, 62, 69, 78, 86), 3.25, highlight=True),
    Cue("gauntlet_loss", "Gauntlet / run over", "outcomes", GAUNTLET,
        "A restrained low impact and a warm, unresolved breath, leaving room to try again.",
        "First transition to lost after pending decisions and the reveal finish.",
        "Views/GauntletFlowViews.swift: LostScreen; Models/GauntletState.swift: endRound",
        "defeat", "card", (38, 50, 57, 60, 65), 2.16),
    Cue("reward_reveal", "Extended Art choices", "outcomes", GAUNTLET,
        "Three spaced card lifts with a quiet prism-like highlight.",
        "When the choose-one-of-three reward row appears; leave a gap after victory.",
        "Views/GauntletRunViews.swift: rewardCell; Models/GauntletState.swift: rewardOptions",
        "progress", "fan", (74, 81, 88), 1.50),
    Cue("reward_claim", "Claim Extended Art", "outcomes", GAUNTLET,
        "A prize seats with a convincing seal and a generous holographic afterglow.",
        "After chooseReward awards the chosen card to the Binder.",
        "Models/GauntletState.swift: chooseReward; Models/GameState.swift: awardExtendedArt",
        "reveal", "card", (50, 62, 74, 81, 90), 2.12, highlight=True),
    Cue("tier_unlock", "A harder tier unlocked", "outcomes", GAUNTLET,
        "An ascending pair of deliberate locks opens into a suspended chord.",
        "ResultsScreen only when lastClear.unlockedTier is non-nil; queue after the claim cue.",
        "Views/GauntletFlowViews.swift: ResultsScreen; Models/GauntletProgress.swift: ClearResult",
        "unlock", "stack", (50, 62, 69, 78, 83), 1.84),
    Cue("trainer_unlock", "A new Trainer joins", "outcomes", GAUNTLET,
        "A character-card arrival with an inviting, warm harmonic signature.",
        "UnlockedTrainersBanner for newly earned Trainers, including after a loss; one cue per banner.",
        "Views/GauntletFlowViews.swift: UnlockedTrainersBanner",
        "victory", "card", (50, 57, 69, 76, 81), 2.04),
)

SCENES = (
    {
        "id": "shortlist",
        "title": "Start here / signature reel",
        "description": "Eight defining gestures, with space between them. Compare A, B, then the hybrid.",
        "events": (
            (0.0, "pack_open"), (1.5, "card_flip"), (2.2, "sell_card"),
            (3.5, "rare"), (5.8, "ultra"), (9.0, "catalyst_attune"),
            (11.3, "boss_round"), (14.3, "gauntlet_win"),
        ),
    },
    {
        "id": "classic",
        "title": "Classic / open, reveal, trade",
        "description": "No flip on the first card. A foil rare layers its sheen under the rarity accent.",
        "events": (
            (0.0, "pack_purchase"), (0.95, "pack_open"),
            (2.0, "card_flip"), (2.6, "card_flip"),
            (3.2, "card_flip"), (3.515, "rare"), (3.515, "foil"),
            (5.5, "keep_card"), (6.25, "bulk_sell"),
        ),
    },
    {
        "id": "grading",
        "title": "Grading / three outcomes",
        "description": "Compare a disappointing result, a solid result and a gem mint. Spaced for audition.",
        "events": (
            (0.0, "grade_start"), (0.75, "grade_low"),
            (2.6, "grade_start"), (3.35, "grade_high"),
            (5.4, "grade_start"), (6.15, "grade_perfect"),
        ),
    },
    {
        "id": "gauntlet",
        "title": "Gauntlet / build, attune, clear",
        "description": "A Showcase decision leads to a Catalyst, a cleared target and a shop upgrade.",
        "events": (
            (0.0, "trainer_select"), (1.0, "run_start"),
            (3.2, "pack_open"), (4.7, "keep_card"),
            (5.5, "catalyst_offer"), (7.5, "catalyst_attune"),
            (9.3, "round_clear"), (11.25, "round_payout"),
            (12.8, "showcase_expand"), (14.3, "round_start"),
        ),
    },
    {
        "id": "championship",
        "title": "Championship / the payoff",
        "description": "Drama is reserved for the stakes. Rewards and unlocks wait their turn.",
        "events": (
            (0.0, "boss_round"), (3.0, "pack_open"),
            (4.4, "ultra"), (4.4, "foil"), (7.6, "gauntlet_win"),
            (11.6, "reward_reveal"), (13.8, "reward_claim"),
            (16.6, "tier_unlock"),
        ),
    },
    {
        "id": "repeat",
        "title": "Fatigue check / rapid decisions",
        "description": "Three alternate takes cycle on repeated gestures. No infinite loop.",
        "events": tuple(
            [(i * 0.36, "card_flip") for i in range(8)]
            + [(3.2 + i * 0.62, "sell_card") for i in range(5)]
        ),
    },
)


def recommended_style(cue):
    """Keep the daily loop tactile; give Gauntlet's rare high-stakes moments space."""
    if cue.id in {
        "ultra", "grade_perfect", "catalyst_offer", "catalyst_attune",
        "boss_round", "gauntlet_win", "reward_claim", "trainer_unlock",
    }:
        return "mythic"
    return "studio"
